import type { Resume } from '../types/resume'

export const demoResume: Resume = {
  version: 2,
  basic: {
    name: '林知远',
    englishName: 'Evan Lin',
    gender: '男',
    birthDate: '2000-05-18',
    phone: '13800001234',
    email: 'evan.lin@example.com',
    city: '上海',
    hometown: '杭州',
    targetCity: '上海',
    targetRole: '机器人软件工程师',
    github: 'https://github.com/evanlin-demo',
    website: 'https://evanlin.example.com',
  },
  education: [
    {
      id: 'edu-1',
      school: '远川科技大学',
      degree: '硕士',
      major: '机械电子工程',
      startDate: '2023-09',
      endDate: '2026-06',
      gpa: '3.78/4.0',
      ranking: '前 10%',
      research: '移动机器人感知与控制',
      description: '研究多传感器融合定位与运动控制。',
    },
  ],
  projects: [
    {
      id: 'project-1',
      name: '面向肩肱节律的上肢外骨骼康复训练方法研究',
      role: '算法与系统负责人',
      startDate: '2024-03',
      endDate: '2025-01',
      description: '围绕上肢康复训练中的肩肱节律协调问题，构建外骨骼辅助训练方法与实验验证流程。',
      responsibilities: '负责运动学建模、控制策略设计、实验数据分析和原型系统联调。',
      techStack: 'Python、MATLAB、ROS 2、C++、传感器融合',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: '星轨机器人科技有限公司',
      department: '自主移动产品部',
      role: '机器人软件实习生',
      startDate: '2025-03',
      endDate: '2025-09',
      description: '参与导航模块性能分析与工具链建设，将现场问题复现时间缩短约 30%。',
    },
  ],
  skills: {
    programming: 'C++、Python、TypeScript',
    tools: 'Git、Docker、CMake、Linux',
    embedded: 'STM32、CAN、UART',
    robotics: 'ROS 2、SLAM、路径规划、运动控制',
    mechanical: 'SolidWorks、基础结构设计',
    english: 'CET-6，可阅读英文技术文档',
    other: '技术写作、跨团队协作',
  },
  libraryItems: [
    {
      id: 'library-project-1',
      itemType: 'group',
      category: 'project',
      title: '面向肩肱节律的上肢外骨骼康复训练方法研究',
      subtitle: '康复机器人 / 控制策略 / 实验验证',
      favorite: true,
      useCount: 0,
      children: [
        {
          id: 'library-project-1-description',
          key: 'description',
          label: '项目描述',
          content: '围绕上肢康复训练中的肩肱节律协调问题，构建外骨骼辅助训练方法与实验验证流程，提升训练动作的一致性和可解释性。',
          useCount: 0,
        },
        {
          id: 'library-project-1-responsibilities',
          key: 'responsibilities',
          label: '项目职责',
          content: '负责运动学建模、控制策略设计、传感器数据处理、实验流程搭建和原型系统联调。',
          useCount: 0,
        },
        {
          id: 'library-project-1-outcome',
          key: 'outcome',
          label: '项目成果',
          content: '完成可复现实验流程和数据分析脚本，形成面向康复训练评估的指标体系与阶段性研究报告。',
          useCount: 0,
        },
        {
          id: 'library-project-1-tech',
          key: 'techStack',
          label: '技术栈',
          content: 'Python、MATLAB、ROS 2、C++、运动学建模、传感器融合',
          useCount: 0,
        },
      ],
    },
    {
      id: 'library-education-1',
      itemType: 'group',
      category: 'education',
      title: '远川科技大学',
      subtitle: '机械电子工程 / 硕士 / 2023-2026',
      favorite: false,
      useCount: 0,
      children: [
        { id: 'library-education-1-school', key: 'school', label: '学校', content: '远川科技大学', useCount: 0 },
        { id: 'library-education-1-major', key: 'major', label: '专业', content: '机械电子工程', useCount: 0 },
        { id: 'library-education-1-degree', key: 'degree', label: '学历', content: '硕士', useCount: 0 },
        { id: 'library-education-1-description', key: 'description', label: '教育经历描述', content: '研究多传感器融合定位与运动控制，关注机器人系统在真实场景中的稳定性。', useCount: 0 },
      ],
    },
    {
      id: 'library-plain-1',
      itemType: 'plain',
      category: 'selfDescription',
      title: '自我评价',
      content: '注重问题拆解与工程闭环，能够从日志、数据和实机表现中快速定位问题，并清晰记录解决方案。',
      favorite: true,
      useCount: 0,
    },
    {
      id: 'library-plain-2',
      itemType: 'plain',
      category: 'commonAnswer',
      title: '职业规划',
      content: '希望持续深耕机器人软件与运动控制，成长为能连接算法、系统和产品落地的工程师。',
      favorite: false,
      useCount: 0,
    },
  ],
  updatedAt: '2026-01-10T08:00:00.000Z',
}
