import type { Resume } from '../types/resume'

export const demoResume: Resume = {
  version: 1,
  basic: {
    name: '林知远',
    englishName: 'Evan Lin',
    gender: '男',
    birthDate: '2000-05-18',
    phone: '13800001234',
    email: 'evan.lin@example.com',
    city: '上海',
    hometown: '杭州',
    targetCity: '上海',
    targetRole: '机器人软件工程师',
    github: 'https://github.com/evanlin-demo',
    website: 'https://evanlin.example.com',
  },
  education: [
    {
      id: 'edu-1',
      school: '远川科技大学',
      degree: '硕士',
      major: '机械电子工程',
      startDate: '2023-09',
      endDate: '2026-06',
      gpa: '3.78/4.0',
      ranking: '前 10%',
      research: '移动机器人感知与控制',
      description: '研究多传感器融合定位与运动控制。',
    },
    {
      id: 'edu-2',
      school: '江城工业大学',
      degree: '本科',
      major: '自动化',
      startDate: '2019-09',
      endDate: '2023-06',
      gpa: '3.62/4.0',
      ranking: '8/126',
      research: '智能控制',
      description: '主修控制原理、机器人学与嵌入式系统。',
    },
  ],
  projects: [
    {
      id: 'project-1',
      name: '室内移动机器人导航系统',
      role: '算法负责人',
      startDate: '2024-03',
      endDate: '2025-01',
      description: '面向复杂室内环境的自主建图、定位与路径规划系统。',
      responsibilities: '负责传感器融合、路径规划模块及实机部署。',
      techStack: 'C++、ROS 2、Python、Eigen',
    },
    {
      id: 'project-2',
      name: '轻量机械臂视觉抓取平台',
      role: '核心开发者',
      startDate: '2023-10',
      endDate: '2024-05',
      description: '基于 RGB-D 相机完成目标识别、位姿估计与抓取。',
      responsibilities: '实现标定流程、视觉节点和抓取状态机。',
      techStack: 'Python、OpenCV、PyTorch、MoveIt',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: '星轨机器人科技有限公司',
      department: '自主移动产品部',
      role: '机器人软件实习生',
      startDate: '2025-03',
      endDate: '2025-09',
      description: '参与导航模块性能分析与工具链建设，将现场问题复现时间缩短约 30%。',
    },
  ],
  skills: {
    programming: 'C++、Python、TypeScript',
    tools: 'Git、Docker、CMake、Linux',
    embedded: 'STM32、CAN、UART',
    robotics: 'ROS 2、SLAM、路径规划、运动控制',
    mechanical: 'SolidWorks、基础结构设计',
    english: 'CET-6，可阅读英文技术文档',
    other: '技术写作、跨团队协作',
  },
  snippets: [
    {
      id: 'snippet-1',
      title: '自我评价',
      content: '注重问题拆解与工程闭环，能够从日志、数据和实机表现中快速定位问题，并清晰记录解决方案。',
      category: 'selfDescription',
      favorite: true,
      useCount: 0,
      updatedAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'snippet-2',
      title: '个人优势',
      content: '具备机器人算法与软件工程的复合背景，重视可维护性、测试和现场可诊断性。',
      category: 'selfDescription',
      favorite: false,
      useCount: 0,
      updatedAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'snippet-3',
      title: '职业规划',
      content: '希望持续深耕机器人软件与运动控制，成长为能连接算法、系统和产品落地的工程师。',
      category: 'commonAnswer',
      favorite: false,
      useCount: 0,
      updatedAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'snippet-4',
      title: '项目介绍 100 字',
      content: '负责室内移动机器人导航系统的定位与规划模块，完成多传感器数据接入、地图构建和路径规划，并通过自动化回放工具提升问题复现效率。',
      category: 'project',
      favorite: true,
      useCount: 0,
      updatedAt: '2026-01-10T08:00:00.000Z',
    },
  ],
  updatedAt: '2026-01-10T08:00:00.000Z',
}
